# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dinesh Weerapurage
email: xydinesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer and open source enthusiast, living in Denver, CO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xydinesh.com" # the base hostname & protocol for your site
twitter_username: xydinesh
github_username:  xydinesh

# Build settings
markdown: kramdown
